-- Propuesta de la semana 5-11 oct 2026. Basada en el calendario publicado en la tabla `juegos`.
-- No incluye marcadores porque la base de datos no los tiene.
insert into public.social_posts (fecha, plataformas, formato, titulo, texto, hashtags, material, notas) values
('2026-10-05','{instagram,facebook}','post','Calendario del sábado 10',
E'🐺 ¡Arranca la semana Wolverines! Este SÁBADO 10 de octubre jugamos en el Tec de Monterrey 🏟️\n\n⏰ 4:00 PM · U10 Mixto · Campo 1\n⏰ 4:50 PM · U12 Fem · Campo 3\n⏰ 4:50 PM · U14 Fem · Campo 4\n⏰ 5:40 PM · U6 Mixto · Campo 1\n⏰ 5:40 PM · U8 Mixto · Campo 3\n⏰ 7:20 PM · U8 Mixto · Campo 1\n⏰ 7:20 PM · U16 Fem · Campo 3\n⏰ 8:10 PM · U12 Var · Campo 2\n⏰ 8:10 PM · U14 Fem · Campo 1\n\n⚠️ El partido de U16 Fem vs Dinos sigue pospuesto.\n\nCalendario completo siempre actualizado: wolverines.mx/games.html\n\n¡Los esperamos con todo el ánimo! 💪',
'#WolverinesTRC #LTLKids #FamiliaWolverines','Diseño con el calendario (1 imagen) o captura de wolverines.mx/games.html','Revisar horarios en games.html antes de publicar; pueden cambiar durante la semana.'),
('2026-10-05','{instagram}','historia','Historia: calendario + enlace',
E'Historia con el calendario del sábado y el sticker de enlace a wolverines.mx/games.html. Texto: "¿A qué hora juega tu equipo? Mira el calendario aquí 👇"',
'','Misma imagen del post de las 5','Historia de 24 h, repetir el viernes.'),
('2026-10-06','{instagram,facebook}','carrusel','Resumen del fin de semana pasado',
E'🙌 ¡Gracias familias Wolverines por un gran fin de semana! Viernes en All Pro (femenil, mixto, varonil y +30) y sábado con todas nuestras categorías LTL Kids. Cada partido nos hace más fuertes como equipo 🐺💙\n\nSi tienes fotos de tu jugador o jugadora, envíalas por mensaje directo y las compartimos.',
'#WolverinesTRC #LTLKids #AllPro #FamiliaWolverines','8–10 fotos del 2 y 3 de octubre (portada con la mejor)','No incluir marcadores si no se tienen confirmados con los coaches.'),
('2026-10-07','{instagram,facebook}','reel','Detrás de cámaras: entrenamiento',
E'🏈 Así se prepara un Wolverine. Esfuerzo, risas y trabajo en equipo en cada entrenamiento. ¡Nos vemos el sábado en cancha! 🐺\n\n¿Quieres ser parte? Escríbenos.',
'#WolverinesTRC #Entrenamiento #FamiliaWolverines','Video vertical de 15–30 s de un entrenamiento (con música libre de derechos)','Cuidar tener autorización de padres para fotos o videos de menores.'),
('2026-10-08','{instagram,facebook}','post','Tienda oficial Wolverines',
E'🛍️ Viste los colores del equipo. Jerseys, gorras, hoodies, playeras, mochilas y más en nuestra tienda oficial.\n\nPide el tuyo aquí: wolverines.mx/tienda.html 💙',
'#WolverinesTRC #TiendaOficial #FamiliaWolverines','Fotos de producto (hay imágenes en el sitio: jersey, gorra, hoodie, playera, mochila, llavero)','Confirmar con administración que los precios y tallas mostrados estén vigentes.'),
('2026-10-08','{instagram}','historia','Historia: agrega WeHunt y Wolve Hub a tu celular',
E'Historia para jugadoras y papás: "Agrega WeHunt (jugadoras) o Wolve Hub (papás) a la pantalla de inicio de tu celular 📲". Pasos: abrir la página en Safari → Compartir → Agregar a pantalla de inicio.',
'','Capturas de pantalla de wolverines.mx/wehunt/ y wolverines.mx/wolvehub.html','Los iconos ya están publicados; funcionan al agregarlos a la pantalla de inicio.'),
('2026-10-09','{instagram,facebook}','post','Previa: mañana jugamos',
E'🔥 ¡MAÑANA es día de juego! Sábado 10 de octubre en el Tec de Monterrey. Revisa el horario de tu categoría en wolverines.mx/games.html y llega con tiempo para el calentamiento.\n\n¡Vamos Wolverines! 🐺',
'#WolverinesTRC #DíaDeJuego #LTLKids','Foto de equipo o diseño con "Mañana jugamos"','Programar para el viernes por la tarde.'),
('2026-10-10','{instagram}','historia','Día de juego: historias en vivo',
E'Serie de historias durante los partidos: llegada del equipo, calentamiento, jugadas y celebraciones. Etiquetar a las categorías que jueguen.',
'','Fotos y videos cortos tomados durante los partidos','Pedir a un coach o voluntario que envíe material a Sandy durante el día.'),
('2026-10-10','{facebook}','post','Hoy jugamos en el Tec',
E'🏟️ ¡HOY jugamos! Primer partido a las 4:00 PM en el Tec de Monterrey. Horarios y campos: wolverines.mx/games.html. ¡A apoyar a nuestros Wolverines! 💪🐺',
'#WolverinesTRC #DíaDeJuego','Foto de portada del equipo','Publicar por la mañana.'),
('2026-10-11','{instagram,facebook}','carrusel','Resumen del sábado + gracias',
E'💙 Gracias por acompañarnos este sábado. Estas son algunas de las mejores imágenes del día. ¿Ya viste a tu jugador o jugadora? Etiquétate y comparte 🐺\n\nLa próxima semana, más Wolverines en acción.',
'#WolverinesTRC #LTLKids #FamiliaWolverines','Mejores 8–10 fotos del sábado 10','Agregar marcadores solo si los coaches los confirman.');
